# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "box-cutter/centos65"

  config.vm.define :web1 do |web|
    web.vm.network "private_network", ip: "192.168.33.11"
  end

  config.vm.define :db1 do |db|
    db.vm.network "private_network", ip: "192.168.33.21"
  end

end
