# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require File.expand_path('../config/application', __FILE__)

Rails.application.load_tasks

unicorn_task = '../server/unicorn/task.rb'
require unicorn_task if File.file? unicorn_task
